# Generated by Django 4.2.20 on 2025-05-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import knowledge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identifier used in prompts like {key}. Only letters, numbers, underscores allowed. Must start with a letter.",
                        max_length=100,
                        validators=[knowledge.models.validate_key_format],
                        verbose_name="Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The content associated with the key.",
                        verbose_name="Value",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_fields",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Field",
                "verbose_name_plural": "Knowledge Fields",
                "ordering": ["key"],
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgefield",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_user_key"
            ),
        ),
    ]
