# Generated by Django 4.2.20 on 2025-05-09 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelanceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.TextField()),
                ("title", models.TextField()),
                ("company", models.TextField()),
                ("end_date", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("remote", models.BooleanField(default=False)),
                ("last_updated", models.TextField(blank=True, null=True)),
                ("skills", models.JSONField(default=list)),
                ("url", models.TextField()),
                ("applications", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("provider", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "freelance_projects",
                "unique_together": {("project_id", "provider")},
            },
        ),
        migrations.CreateModel(
            name="FreelanceProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password_encrypted", models.TextField()),
                ("link_1", models.TextField()),
                ("link_2", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelance_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Freelance Provider Credential",
                "verbose_name_plural": "Freelance Provider Credentials",
                "ordering": ["user", "username"],
                "unique_together": {("user", "username")},
            },
        ),
    ]
