# Generated by Django 4.2.20 on 2025-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelanceprovidercredential",
            name="link_3",
            field=models.TextField(blank=True, default=""),
        ),
    ]
