# Generated by Django 4.2.20 on 2025-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0002_freelanceprovidercredential_link_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelanceproject",
            name="project_id",
            field=models.TextField(unique=True),
        ),
    ]
