# Generated by Django 4.2.20 on 2025-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0004_freelanceglobalconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelanceproject",
            name="project_badge",
            field=models.TextField(blank=True, null=True),
        ),
    ]
