# Generated by Django 4.2.20 on 2025-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Unique identifier for the prompt (e.g., 'email_correction', 'suggestion_subject').",
                        max_length=100,
                        unique=True,
                        verbose_name="Name/Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what the prompt is used for.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The prompt template itself. Use placeholders like {context} or {email_body}.",
                        verbose_name="Prompt Content",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("google_gemini", "Google Gemini"),
                            ("groq", "Groq"),
                        ],
                        default="groq",
                        help_text="The AI provider to use for this prompt.",
                        max_length=50,
                        verbose_name="AI Provider",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Specific model name from the provider (e.g., 'gpt-4-turbo', 'gemini-1.5-pro-latest', 'llama3-70b-8192').",
                        max_length=100,
                        verbose_name="Model Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "ordering": ["name"],
            },
        ),
    ]
