# Generated by Django 5.0.7 on 2025-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="folder_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Name des IMAP-Ordners",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["folder_name"], name="core_email_folder__122283_idx"
            ),
        ),
    ]
