# Generated by Django 5.0.7 on 2025-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_email_folder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="last_sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
