# Generated by Django 5.0.7 on 2025-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_emailaccount_last_sync_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="received_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
