# Generated by Django 5.0.7 on 2025-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_email_received_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="ai_processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitstempel der letzten AI-Verarbeitung",
                null=True,
            ),
        ),
    ]
