# Generated by Django 4.2.20 on 2025-04-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["-created_at"]},
        ),
    ]
