# Generated by Django 4.2.20 on 2025-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_attachment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisuggestion",
            name="intent_summary",
            field=models.CharField(
                blank=True,
                help_text="Kurze Intent-Zusammenfassung (max. 5 Worte)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aisuggestion",
            name="suggested_subject",
            field=models.CharField(
                blank=True,
                help_text="Vorgeschlagener Betreff für die Antwort",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="aisuggestion",
            name="title",
            field=models.CharField(
                help_text="Kurzer Titel/Zusammenfassung des Vorschlags", max_length=100
            ),
        ),
    ]
