# Generated by Django 4.2.20 on 2025-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_aisuggestion_intent_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="medium_summary",
            field=models.CharField(
                blank=True,
                help_text="Mittellange Zusammenfassung (6-12 Worte)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="short_summary",
            field=models.CharField(
                blank=True,
                help_text="Sehr kurze Zusammenfassung (max 5 Worte)",
                max_length=50,
                null=True,
            ),
        ),
    ]
