# Generated by Django 4.2.20 on 2025-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_email_medium_summary_email_short_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICredential",
            fields=[
                (
                    "provider",
                    models.CharField(
                        choices=[("groq", "Groq")],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True, help_text="Encrypted API Key", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Credential",
                "verbose_name_plural": "API Credentials",
                "ordering": ["provider"],
            },
        ),
    ]
