# Generated by Django 4.2.20 on 2025-04-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_apicredential"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APICredential",
        ),
    ]
