# Generated by Django 4.2.20 on 2025-04-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_delete_apicredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google_gemini", "Google Gemini"), ("groq", "Groq")],
                        max_length=50,
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(blank=True, help_text="Verschlüsselter API Key"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Credential",
                "verbose_name_plural": "API Credentials",
                "ordering": ["user", "provider"],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
