# Generated by Django 4.2.20 on 2025-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_apicredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableApiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google_gemini", "Google Gemini"), ("groq", "Groq")],
                        db_index=True,
                        help_text="The API provider this model belongs to.",
                        max_length=50,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="The unique identifier of the model as provided by the API.",
                        max_length=255,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="A human-readable name for the model (optional).",
                        max_length=255,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this model was first discovered or last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Available API Model",
                "verbose_name_plural": "Available API Models",
                "ordering": ["provider", "model_id"],
                "unique_together": {("provider", "model_id")},
            },
        ),
    ]
