# Generated by Django 4.2.20 on 2025-04-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_availableapimodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicredential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_credentials",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_accounts",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.user"
            ),
        ),
    ]
