# Generated by Django 4.2.20 on 2025-05-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_apicredential_user_alter_contact_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the request was initiated.",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="AI provider used (e.g., 'groq', 'google_gemini').",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Specific model used.", max_length=100),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The exact prompt sent to the API."),
                ),
                (
                    "raw_response_text",
                    models.TextField(
                        blank=True,
                        help_text="The raw text response received from the API.",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code of the API response.",
                        null=True,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the API call in milliseconds.",
                        null=True,
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the API call was considered successful (e.g., got a valid response).",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if the call failed or response processing failed.",
                    ),
                ),
                (
                    "triggering_source",
                    models.CharField(
                        blank=True,
                        help_text="Where the request originated (e.g., 'generate_suggestions_task', 'api_key_check').",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the request (if available).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Request Log",
                "verbose_name_plural": "AI Request Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
