# Generated by Django 4.2.20 on 2025-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_airequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="markdown_body",
            field=models.TextField(
                blank=True,
                help_text="Markdown version generated from body_html",
                null=True,
            ),
        ),
    ]
