# Generated by Django 4.2.20 on 2025-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_email_markdown_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="flags",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name="email",
            name="bcc_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="emails_received_bcc", to="core.contact"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="cc_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="emails_received_cc", to="core.contact"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="folder_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="markdown_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="to_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="emails_received_to", to="core.contact"
            ),
        ),
    ]
