# Generated by Django 4.2.20 on 2025-05-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_aiaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisuggestion",
            name="content_backup",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aisuggestion",
            name="subject_backup",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
