# Generated by Django 4.2.20 on 2025-05-07 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_aisuggestion_content_backup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISuggestionEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[("subject", "Subject"), ("body", "Body")],
                        max_length=16,
                    ),
                ),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edit_type",
                    models.CharField(
                        choices=[("manual", "Manuell"), ("ai", "KI")],
                        default="manual",
                        max_length=8,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="core.aisuggestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
